/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.24
 * Generated at: 2024-06-20 02:36:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.page;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class thongtinhanghoa_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar", Long.valueOf(1717151742582L));
    _jspx_dependants.put("jar:file:/H:/Hoang/QL_BH_Java_Web/Lab_02/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/QL_BH/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar!/META-INF/fmt.tld", Long.valueOf(1602848772000L));
    _jspx_dependants.put("jar:file:/H:/Hoang/QL_BH_Java_Web/Lab_02/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/QL_BH/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar!/META-INF/c.tld", Long.valueOf(1602848772000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>Siêu thị Ogani</title>\r\n");
      out.write("<meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("<meta content=\"\" name=\"keywords\">\r\n");
      out.write("<meta content=\"\" name=\"description\">\r\n");
      out.write("\r\n");
      out.write("<!-- Google Web Fonts -->\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&family=Raleway:wght@600;800&display=swap\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Icon Font Stylesheet -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://use.fontawesome.com/releases/v5.15.4/css/all.css\" />\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Libraries Stylesheet -->\r\n");
      out.write("<link href=\"page/lib/lightbox/css/lightbox.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"page/lib/owlcarousel/assets/owl.carousel.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Customized Bootstrap Stylesheet -->\r\n");
      out.write("<link href=\"page/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Template Stylesheet -->\r\n");
      out.write("<link href=\"page/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"icon\" type=\"image/x-icon\" href=\"page/img/title.ico\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<!-- Spinner Start -->\r\n");
      out.write("	<div id=\"spinner\"\r\n");
      out.write("		class=\"show w-100 vh-100 bg-white position-fixed translate-middle top-50 start-50  d-flex align-items-center justify-content-center\">\r\n");
      out.write("		<div class=\"spinner-grow text-primary\" role=\"status\"></div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- Spinner End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Navbar start -->\r\n");
      out.write("	<div class=\"container-fluid fixed-top\">\r\n");
      out.write("		<div class=\"container topbar bg-primary d-none d-lg-block\">\r\n");
      out.write("			<div class=\"d-flex justify-content-between\">\r\n");
      out.write("				<div class=\"top-info ps-2 fw-bold\">\r\n");
      out.write("					<small class=\"me-3\"><i\r\n");
      out.write("						class=\"fas fa-map-marker-alt me-2 text-secondary\"></i> <a\r\n");
      out.write("						href=\"https://www.google.com/maps/search/89+%C4%90.+L%C3%AA+%C4%90%E1%BB%A9c+Th%E1%BB%8D,+M%E1%BB%B9+%C4%90%C3%ACnh,+T%E1%BB%AB+Li%C3%AAm,+H%C3%A0+N%E1%BB%99i/@21.0283486,105.7669354,17z/data=!3m1!4b1?hl=vi-VN&entry=ttu\"\r\n");
      out.write("						class=\"text-white\">89 Đ. Lê Đức Thọ, Mỹ Đình, Từ Liêm, Hà Nội</a></small>\r\n");
      out.write("					<small class=\"me-3\"><i\r\n");
      out.write("						class=\"fas fa-envelope me-2 text-secondary\"></i><a\r\n");
      out.write("						href=\"https://www.google.com/intl/vi/gmail/about/\"\r\n");
      out.write("						class=\"text-white\">ogani@gmail.com</a></small>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"top-link pe-2 fw-bold\">\r\n");
      out.write("					<a href=\"trangchu\" class=\"text-white\"><small\r\n");
      out.write("						class=\"text-white mx-2\">Chính sách bảo mật</small>/</a> <a\r\n");
      out.write("						href=\"trangchu\" class=\"text-white\"><small\r\n");
      out.write("						class=\"text-white mx-2\">Điều khoản sử dụng</small>/</a> <a\r\n");
      out.write("						href=\"trangchu\" class=\"text-white\"><small\r\n");
      out.write("						class=\"text-white ms-2\">Bán hàng và hoàn tiền</small></a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"container px-0\">\r\n");
      out.write("			<nav class=\"navbar navbar-light bg-white navbar-expand-xl\">\r\n");
      out.write("				<a href=\"trangchu\" class=\"navbar-brand\">\r\n");
      out.write("					<h1 class=\"text-primary display-6\">Ogani</h1>\r\n");
      out.write("				</a>\r\n");
      out.write("				<button class=\"navbar-toggler py-2 px-3\" type=\"button\"\r\n");
      out.write("					data-bs-toggle=\"collapse\" data-bs-target=\"#navbarCollapse\">\r\n");
      out.write("					<span class=\"fa fa-bars text-primary\"></span>\r\n");
      out.write("				</button>\r\n");
      out.write("				<div class=\"collapse navbar-collapse bg-white\" id=\"navbarCollapse\">\r\n");
      out.write("					<div class=\"navbar-nav mx-auto fw-bold\">\r\n");
      out.write("						<a href=\"trangchu\" class=\"nav-item nav-link fs-5\">Trang chủ</a> <a\r\n");
      out.write("							href=\"hanghoa\" class=\"nav-item nav-link fs-5\">Hàng hóa</a>\r\n");
      out.write("						<div class=\"nav-item dropdown\">\r\n");
      out.write("							<a href=\"#\" class=\"nav-link dropdown-toggle fs-5\"\r\n");
      out.write("								data-bs-toggle=\"dropdown\">Danh mục</a>\r\n");
      out.write("							<div class=\"dropdown-menu m-0 bg-secondary rounded-0\">\r\n");
      out.write("								<a href=\"giohang\" class=\"dropdown-item active fs-5\">Giỏ hàng</a>\r\n");
      out.write("								<a href=\"dathang\" class=\"dropdown-item fs-5\">Thanh toán</a><a\r\n");
      out.write("									href=\"theodoidh\" class=\"dropdown-item fs-5\">Theo dõi đơn\r\n");
      out.write("									hàng</a> <a href=\"tinnhankh\" class=\"dropdown-item fs-5\">Phản\r\n");
      out.write("									hồi khách hàng</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<a href=\"phanhoi\" class=\"nav-item nav-link fs-5\">Liên hệ</a>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"d-flex m-3 me-0\">\r\n");
      out.write("						<button\r\n");
      out.write("							class=\"btn-search btn border border-secondary btn-md-square rounded-circle bg-white me-4\"\r\n");
      out.write("							data-bs-toggle=\"modal\" data-bs-target=\"#searchModal\">\r\n");
      out.write("							<i class=\"fas fa-search text-primary\"></i>\r\n");
      out.write("						</button>\r\n");
      out.write("						<a href=\"giohang\" class=\"position-relative me-4 my-auto\"> <i\r\n");
      out.write("							class=\"fa fa-cart-plus fa-2x\"></i> <span\r\n");
      out.write("							class=\"position-absolute bg-secondary rounded-circle d-flex align-items-center justify-content-center text-dark px-1\"\r\n");
      out.write("							style=\"top: -5px; left: 25px; height: 20px; min-width: 20px;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.size}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("						</a>\r\n");
      out.write("						");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("						<div\r\n");
      out.write("							class=\"nav-item dropdown ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\">\r\n");
      out.write("							<a href=\"khachhang\" class=\"nav-link dropdown-toggle my-auto\"\r\n");
      out.write("								data-bs-toggle=\"dropdown\"> <i class=\"fas fa-user fa-2x\"></i>\r\n");
      out.write("							</a>\r\n");
      out.write("							<div class=\"dropdown-menu m-0 bg-secondary rounded-0\">\r\n");
      out.write("								<a href=\"login\" class=\"dropdown-item active fs-5\">Đăng nhập</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div\r\n");
      out.write("							class=\"nav-item dropdown ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\">\r\n");
      out.write("							<a href=\"#\" class=\"nav-link dropdown-toggle my-auto\"\r\n");
      out.write("								data-bs-toggle=\"dropdown\"> <i class=\"fas fa-user fa-2x\"></i>\r\n");
      out.write("								<span class=\"fw-bold fs-4\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.kh.ten_kh}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("							</a>\r\n");
      out.write("							<div class=\"dropdown-menu m-0 bg-secondary rounded-0\">\r\n");
      out.write("								<a href=\"khachhang\" class=\"dropdown-item active fs-5\">Thông\r\n");
      out.write("									tin tài khoản</a> <a href=\"logout\" class=\"dropdown-item fs-5\">Đăng\r\n");
      out.write("									xuất</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</nav>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- Navbar End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Single Page Header start -->\r\n");
      out.write("	<div class=\"container-fluid page-header py-5\"\r\n");
      out.write("		style=\"background: linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url(page/img/cart-page-header-img.jpg);\">\r\n");
      out.write("		<h1 class=\"text-center text-white display-6\">Chi tiết hàng hóa</h1>\r\n");
      out.write("		<ol class=\"breadcrumb justify-content-center mb-0\">\r\n");
      out.write("			<li class=\"breadcrumb-item\"><a href=\"trangchu\">Trang chủ</a></li>\r\n");
      out.write("			<li class=\"breadcrumb-item\"><a href=\"hanghoa\">Hàng hóa</a></li>\r\n");
      out.write("			<li class=\"breadcrumb-item active text-white\">Chi tiết hàng hóa</li>\r\n");
      out.write("		</ol>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- Single Page Header End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Fruits Shop Start-->\r\n");
      out.write("	<div class=\"container-fluid fruite py-5\">\r\n");
      out.write("		<div class=\"container py-5\">\r\n");
      out.write("			<h1 class=\"mb-4\">Thông tin hàng hóa</h1>\r\n");
      out.write("			");
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("			<div class=\"row g-4 mb-5\">\r\n");
      out.write("				<div class=\"col-lg-8 col-xl-9\">\r\n");
      out.write("					<div class=\"row g-4\">\r\n");
      out.write("						<div class=\"col-lg-6\">\r\n");
      out.write("							<div class=\"border rounded\">\r\n");
      out.write("								<a href=\"\"> <img src=\"page/img/hanghoa/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${d.anh}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("									class=\"img-fluid rounded\" alt=\"\" width=\"469px\" height=\"469px\">\r\n");
      out.write("								</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-lg-6\">\r\n");
      out.write("							<h4 class=\"fw-bold mb-3\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${d.ten_hang}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h4>\r\n");
      out.write("\r\n");
      out.write("							<p class=\"mb-3\">Loại hàng hóa: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${d.ten_loai_hang}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("							<p class=\"mb-3\">Nhà cung cấp: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${d.ten_nha_cung_cap}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("							<h5 class=\"fw-bold mb-3\">\r\n");
      out.write("								Giá:\r\n");
      out.write("								");
      if (_jspx_meth_fmt_005fformatNumber_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("								đ\r\n");
      out.write("							</h5>\r\n");
      out.write("							<h5 class=\"fw-bold mb-3\">ĐVT: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${d.don_vi_tinh}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h5>\r\n");
      out.write("							<h5 class=\"fw-bold mb-3\">Số lượng tồn: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${d.so_luong}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h5>\r\n");
      out.write("							<p class=\"mb-4\">Ghi chú: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${d.ghi_chu}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("							<div class=\"input-group quantity mb-5\" style=\"width: 100px;\">\r\n");
      out.write("								<div class=\"input-group-btn\">\r\n");
      out.write("									<button\r\n");
      out.write("										class=\"btn btn-sm btn-minus rounded-circle bg-light border\">\r\n");
      out.write("										<i class=\"fa fa-minus\"></i>\r\n");
      out.write("									</button>\r\n");
      out.write("								</div>\r\n");
      out.write("								<input type=\"text\"\r\n");
      out.write("									class=\"form-control form-control-sm text-center border-0 fw-bold fs-6\"\r\n");
      out.write("									value=\"1\" name=\"number\">\r\n");
      out.write("								<div class=\"input-group-btn\">\r\n");
      out.write("									<button\r\n");
      out.write("										class=\"btn btn-sm btn-plus rounded-circle bg-light border\">\r\n");
      out.write("										<i class=\"fa fa-plus\"></i>\r\n");
      out.write("									</button>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<a href=\"themhhgiohang?ma_hang=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${d.ma_hang}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&so_luong=\"\r\n");
      out.write("								id=\"addToCartBtn\" onclick=\"err('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${d.ten_hang}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('\'');
      out.write(',');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${d.so_luong}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")\"\r\n");
      out.write("								class=\"btn border border-secondary rounded-pill px-4 py-2 mb-4 text-primary\"><i\r\n");
      out.write("								class=\"fa fa-shopping-bag me-2 text-primary\"></i> Thêm vào giỏ\r\n");
      out.write("								hàng</a>\r\n");
      out.write("							<script>\r\n");
      out.write("								document.addEventListener(\"DOMContentLoaded\", function() {\r\n");
      out.write("								var inputNumber = document.querySelector('input[name=\"number\"]');\r\n");
      out.write("								var addToCartBtn = document.getElementById('addToCartBtn');\r\n");
      out.write("								\r\n");
      out.write("								addToCartBtn.addEventListener('click', function(event) {\r\n");
      out.write("									event.preventDefault();\r\n");
      out.write("									var so_luong = inputNumber.value;\r\n");
      out.write("									this.href = \"themhhgiohang?thongtinct=1&ma_hang=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${d.ma_hang}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&so_luong=\" + so_luong;\r\n");
      out.write("									window.location.href = this.href;\r\n");
      out.write("								});\r\n");
      out.write("							});\r\n");
      out.write("								function err(ten_hang, so_luong_ton) {\r\n");
      out.write("									var inputNumber1 = document.querySelector('input[name=\"number\"]');\r\n");
      out.write("								    var so_luong1 = parseInt(inputNumber1.value);\r\n");
      out.write("\r\n");
      out.write("								    if (parseInt(so_luong_ton) < so_luong1) {\r\n");
      out.write("								        alert(ten_hang + \" còn tồn \" + so_luong_ton + \". Vui lòng chọn mặt hàng khác\");\r\n");
      out.write("								    } else if (so_luong_ton == 0) {\r\n");
      out.write("								        alert(ten_hang + \" còn tồn \" + so_luong_ton + \". Vui lòng chọn mặt hàng khác\");\r\n");
      out.write("								    } \r\n");
      out.write("                                }\r\n");
      out.write("							</script>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-lg-4 col-xl-3\">\r\n");
      out.write("					<div class=\"row g-4 fruite\">\r\n");
      out.write("						<div class=\"col-lg-12\">\r\n");
      out.write("							<div class=\"mb-4\">\r\n");
      out.write("								<h4>Loại hàng hóa</h4>\r\n");
      out.write("								<ul class=\"list-unstyled fruite-categorie\">\r\n");
      out.write("									");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("								</ul>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"fw-bold pt-5\">Những hàng hóa tương tự</div>\r\n");
      out.write("			<div class=\"vesitable\">\r\n");
      out.write("				<div class=\"owl-carousel vegetable-carousel justify-content-center\">\r\n");
      out.write("					");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- Fruits Shop End-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Footer Start -->\r\n");
      out.write("	<div class=\"container-fluid bg-dark text-white-50 footer pt-5 mt-5\">\r\n");
      out.write("		<div class=\"container py-5\">\r\n");
      out.write("			<div class=\"pb-4 mb-4\"\r\n");
      out.write("				style=\"border-bottom: 1px solid rgba(226, 175, 24, 0.5);\">\r\n");
      out.write("				<div class=\"row g-4\">\r\n");
      out.write("					<div class=\"col-lg-3\">\r\n");
      out.write("						<a href=\"#\">\r\n");
      out.write("							<h1 class=\"text-primary mb-0\">Ogani</h1>\r\n");
      out.write("							<p class=\"text-secondary mb-0\">Siêu thị trực tuyến</p>\r\n");
      out.write("						</a>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-lg-9\">\r\n");
      out.write("						<div class=\"d-flex justify-content-end pt-3\">\r\n");
      out.write("							<a\r\n");
      out.write("								class=\"btn  btn-outline-secondary me-2 btn-md-square rounded-circle\"\r\n");
      out.write("								href=\"\"><i class=\"fab fa-twitter\"></i></a> <a\r\n");
      out.write("								class=\"btn btn-outline-secondary me-2 btn-md-square rounded-circle\"\r\n");
      out.write("								href=\"\"><i class=\"fab fa-facebook-f\"></i></a> <a\r\n");
      out.write("								class=\"btn btn-outline-secondary me-2 btn-md-square rounded-circle\"\r\n");
      out.write("								href=\"\"><i class=\"fab fa-youtube\"></i></a> <a\r\n");
      out.write("								class=\"btn btn-outline-secondary btn-md-square rounded-circle\"\r\n");
      out.write("								href=\"\"><i class=\"fab fa-linkedin-in\"></i></a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"row g-5\">\r\n");
      out.write("				<div class=\"col-lg-4 col-md-6\">\r\n");
      out.write("					<div class=\"d-flex flex-column text-start footer-item\">\r\n");
      out.write("						<h4 class=\"text-light mb-3\">Thông tin cửa hàng</h4>\r\n");
      out.write("						<a class=\"btn-link\" href=\"\">Chính sách bảo mật</a> <a\r\n");
      out.write("							class=\"btn-link\" href=\"\">Điều khoản và điều kiện</a> <a\r\n");
      out.write("							class=\"btn-link\" href=\"\">Chính sách hoàn trả</a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-lg-4 col-md-6\">\r\n");
      out.write("					<div class=\"d-flex flex-column text-start footer-item\">\r\n");
      out.write("						<h4 class=\"text-light mb-3\">Tài khoản</h4>\r\n");
      out.write("						<a class=\"btn-link\" href=\"\">Tài khoản của tôi</a> <a\r\n");
      out.write("							class=\"btn-link\" href=\"\">Hàng hóa</a> <a class=\"btn-link\" href=\"\">Giỏ\r\n");
      out.write("							hàng</a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-lg-4 col-md-6\">\r\n");
      out.write("					<div class=\"footer-item\">\r\n");
      out.write("						<h4 class=\"text-light mb-3\">Liên hệ</h4>\r\n");
      out.write("						<p>Địa chỉ: 89 Đ. Lê Đức Thọ, Mỹ Đình, Từ Liêm, Hà Nội</p>\r\n");
      out.write("						<p>Email: ogani@gmail.com</p>\r\n");
      out.write("						<p>Điện thoại: 0359782629</p>\r\n");
      out.write("						<p>Thanh toán được chấp nhận</p>\r\n");
      out.write("						<img src=\"page/img/payment.png\" class=\"img-fluid\" alt=\"\">\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- Footer End -->\r\n");
      out.write("\r\n");
      out.write("	<!-- Copyright Start -->\r\n");
      out.write("	<div class=\"container-fluid copyright bg-dark py-4\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-md-6 text-center text-md-start mb-3 mb-md-0\">\r\n");
      out.write("					<span class=\"text-light\"><a href=\"index.html\"><i\r\n");
      out.write("							class=\"fas fa-copyright text-light me-2\"></i>Trang web </a>, Mọi\r\n");
      out.write("						quyền được bảo lưu.</span>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-6 my-auto text-center text-md-end text-white\">\r\n");
      out.write("					Được thiết kế bởi <a class=\"border-bottom\"\r\n");
      out.write("						href=\"https://vi.wikipedia.org/wiki/Oracle_Corporation\">\r\n");
      out.write("						Oracle Corporation</a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- Copyright End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Back to Top -->\r\n");
      out.write("	<a href=\"#\"\r\n");
      out.write("		class=\"btn btn-primary border-3 border-primary rounded-circle back-to-top\"><i\r\n");
      out.write("		class=\"fa fa-arrow-up\"></i></a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- JavaScript Libraries -->\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("	<script src=\"page/lib/easing/easing.min.js\"></script>\r\n");
      out.write("	<script src=\"page/lib/waypoints/waypoints.min.js\"></script>\r\n");
      out.write("	<script src=\"page/lib/lightbox/js/lightbox.min.js\"></script>\r\n");
      out.write("	<script src=\"page/lib/owlcarousel/owl.carousel.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("	<!-- Template Javascript -->\r\n");
      out.write("	<script src=\"page/js/main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /page/thongtinhanghoa.jsp(115,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("ten_kh");
      // /page/thongtinhanghoa.jsp(115,6) name = value type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/page/thongtinhanghoa.jsp(115,6) '${sessionScope.kh.ten_kh}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${sessionScope.kh.ten_kh}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /page/thongtinhanghoa.jsp(117,32) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ten_kh != null}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("visually-hidden");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /page/thongtinhanghoa.jsp(126,32) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ten_kh == null}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("visually-hidden");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent(null);
      // /page/thongtinhanghoa.jsp(163,3) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("d");
      // /page/thongtinhanghoa.jsp(163,3) name = value type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/page/thongtinhanghoa.jsp(163,3) '${requestScope.data}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${requestScope.data}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    boolean _jspx_th_fmt_005fformatNumber_005f0_reused = false;
    try {
      _jspx_th_fmt_005fformatNumber_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatNumber_005f0.setParent(null);
      // /page/thongtinhanghoa.jsp(181,8) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${d.gia_ban}", java.lang.Object.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      // /page/thongtinhanghoa.jsp(181,8) name = type type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f0.setType("number");
      int _jspx_eval_fmt_005fformatNumber_005f0 = _jspx_th_fmt_005fformatNumber_005f0.doStartTag();
      if (_jspx_th_fmt_005fformatNumber_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f0);
      _jspx_th_fmt_005fformatNumber_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /page/thongtinhanghoa.jsp(241,9) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("d1");
      // /page/thongtinhanghoa.jsp(241,9) name = items type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/page/thongtinhanghoa.jsp(241,9) '${requestScope.ma_lh}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${requestScope.ma_lh}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("										<li>\r\n");
            out.write("											<div\r\n");
            out.write("												class=\"d-flex justify-content-between fruite-name fw-bold fs-5\">\r\n");
            out.write("												<a href=\"hanghoa?ma_lh=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${d1.ma_loai_hang}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"><i\r\n");
            out.write("													class=\"fas fa-apple-alt me-2\"></i>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${d1.ten_loai_hang}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a> <span>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${d1.count}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\r\n");
            out.write("											</div>\r\n");
            out.write("										</li>\r\n");
            out.write("									");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /page/thongtinhanghoa.jsp(260,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("d12");
      // /page/thongtinhanghoa.jsp(260,5) name = items type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/page/thongtinhanghoa.jsp(260,5) '${requestScope.data1}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${requestScope.data1}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("						<div\r\n");
            out.write("							class=\"border border-primary rounded position-relative vesitable-item\"\r\n");
            out.write("							onclick=\"window.location='thongtinhh?ma_hang=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${d12.ma_hang}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("';\">\r\n");
            out.write("							<div class=\"vesitable-img border border-primary\">\r\n");
            out.write("								<img src=\"page/img/hanghoa/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${d12.anh}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"\r\n");
            out.write("									class=\"img-fluid w-100 rounded-top\" alt=\"\">\r\n");
            out.write("							</div>\r\n");
            out.write("							<div class=\"p-4 rounded-bottom\">\r\n");
            out.write("								<h4 class=\"d-flex justify-content-center text-dark fs-3 fw-bold\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${d12.ten_hang}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</h4>\r\n");
            out.write("								<p class=\"text-dark fs-6 fw-bold mb-2\">Mã hàng hóa:\r\n");
            out.write("									HH_");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${d12.ma_hang}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</p>\r\n");
            out.write("								<p class=\"text-dark fs-6 fw-bold mb-2\">Số lượng tồn:\r\n");
            out.write("									");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${d12.so_luong}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</p>\r\n");
            out.write("								<p class=\"text-dark fs-6 fw-bold mb-2\">Ghi chú:\r\n");
            out.write("									");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${d12.ghi_chu}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</p>\r\n");
            out.write("								<p\r\n");
            out.write("									class=\"text-dark fs-5 fw-bold mb-2 d-flex justify-content-center\">\r\n");
            out.write("									");
            if (_jspx_meth_fmt_005fformatNumber_005f1(_jspx_th_c_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
              return true;
            out.write("\r\n");
            out.write("									đ / ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${d12.don_vi_tinh}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\r\n");
            out.write("								</p>\r\n");
            out.write("								<div class=\"d-flex justify-content-center flex-lg-wrap\">\r\n");
            out.write("									<a href=\"themhhgiohang?ma_hang=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${d12.ma_hang}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("&so_luong=1\"\r\n");
            out.write("										class=\"btn border border-secondary rounded-pill px-3 text-primary mt-2\"><i\r\n");
            out.write("										class=\"fa fa-shopping-bag me-2 text-primary\"></i> Thêm vào giỏ\r\n");
            out.write("										hàng</a>\r\n");
            out.write("								</div>\r\n");
            out.write("							</div>\r\n");
            out.write("						</div>\r\n");
            out.write("					");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f1(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f1, jakarta.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f1 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    boolean _jspx_th_fmt_005fformatNumber_005f1_reused = false;
    try {
      _jspx_th_fmt_005fformatNumber_005f1.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatNumber_005f1.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f1);
      // /page/thongtinhanghoa.jsp(278,9) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${d12.gia_ban}", java.lang.Object.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      // /page/thongtinhanghoa.jsp(278,9) name = type type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f1.setType("number");
      int _jspx_eval_fmt_005fformatNumber_005f1 = _jspx_th_fmt_005fformatNumber_005f1.doStartTag();
      if (_jspx_th_fmt_005fformatNumber_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f1);
      _jspx_th_fmt_005fformatNumber_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f1, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f1_reused);
    }
    return false;
  }
}
