/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.24
 * Generated at: 2024-06-19 06:15:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class hd_005fbh_005fct_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar", Long.valueOf(1717151742582L));
    _jspx_dependants.put("jar:file:/H:/Hoang/QL_BH_Java_Web/Lab_02/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/QL_BH/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar!/META-INF/fmt.tld", Long.valueOf(1602848772000L));
    _jspx_dependants.put("jar:file:/H:/Hoang/QL_BH_Java_Web/Lab_02/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/QL_BH/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar!/META-INF/c.tld", Long.valueOf(1602848772000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("<title>Siêu thị Organi</title>\r\n");
      out.write("<!-- Icon Title -->\r\n");
      out.write("<link rel=\"icon\" type=\"image/x-icon\" href=\"../page/img/title.ico\">\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap Core CSS -->\r\n");
      out.write("<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- MetisMenu CSS -->\r\n");
      out.write("<link href=\"css/metisMenu.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- DataTables CSS -->\r\n");
      out.write("<link href=\"css/dataTables/dataTables.bootstrap.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- DataTables Responsive CSS -->\r\n");
      out.write("<link href=\"css/dataTables/dataTables.responsive.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Custom CSS -->\r\n");
      out.write("<link href=\"css/startmin.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Custom Fonts -->\r\n");
      out.write("<link href=\"css/font-awesome.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<style>\r\n");
      out.write("th, tbody {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<div id=\"wrapper\">\r\n");
      out.write("\r\n");
      out.write("		<!-- Navigation -->\r\n");
      out.write("		<nav class=\"navbar navbar-inverse navbar-fixed-top\" role=\"navigation\">\r\n");
      out.write("			<ul class=\"nav navbar-nav navbar-left navbar-top-links\">\r\n");
      out.write("				<li><a href=\"http://localhost:8000/QL_BH/\"><i\r\n");
      out.write("						class=\"fa fa-home fa-fw\"></i> Website</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("\r\n");
      out.write("			<ul class=\"nav navbar-right navbar-top-links\">\r\n");
      out.write("				<li class=\"dropdown\"><a class=\"dropdown-toggle\"\r\n");
      out.write("					data-toggle=\"dropdown\" href=\"#\"> <i class=\"fa fa-user fa-fw\"></i>\r\n");
      out.write("						Xin chào, ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.account.ho_ten_nv}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("<b class=\"caret\"></b>\r\n");
      out.write("				</a>\r\n");
      out.write("					<ul class=\"dropdown-menu dropdown-user\">\r\n");
      out.write("						<li><a href=\"thongtintk\"><i class=\"fa fa-user fa-fw\"></i>\r\n");
      out.write("								Thông tin tài khoản</a></li>\r\n");
      out.write("\r\n");
      out.write("						<li class=\"divider\"></li>\r\n");
      out.write("						<li><a href=\"dangxuat\"><i class=\"fa fa-sign-out fa-fw\"></i>\r\n");
      out.write("								Đăng xuất</a></li>\r\n");
      out.write("					</ul></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("			<!-- /.navbar-top-links -->\r\n");
      out.write("		</nav>\r\n");
      out.write("\r\n");
      out.write("		<aside class=\"sidebar navbar-default\" role=\"navigation\">\r\n");
      out.write("			<div class=\"sidebar-nav navbar-collapse\">\r\n");
      out.write("				<ul class=\"nav\" id=\"side-menu\">\r\n");
      out.write("					<li class=\"text-center\"><img src=\"../page/img/logo.png\"></li>\r\n");
      out.write("					<li><a href=\"trangchu\" class=\"active\"><i\r\n");
      out.write("							class=\"fa fa-dashboard fa-fw\"></i> Tổng quan</a></li>\r\n");
      out.write("\r\n");
      out.write("					<li><a href=\"hanghoa\"><i class=\"fa fa-table fa-fw\"></i>\r\n");
      out.write("							Hàng hóa</a></li>\r\n");
      out.write("					<li><a href=\"nhacungcap\"><i class=\"fa fa-cubes fa-fw\"></i>\r\n");
      out.write("							Nhà cung cấp</a></li>\r\n");
      out.write("					<li><a href=\"loaihanghoa\"><i class=\"fa fa-sitemap fa-fw\"></i>\r\n");
      out.write("							Loại hàng hóa</a></li>\r\n");
      out.write("					<li class=\"active\">\r\n");
      out.write("                        <a href=\"#\"><i class=\"fa fa-wpforms fa-fw\"></i> Hóa đơn<span\r\n");
      out.write("						class=\"fa arrow\"></span></a>\r\n");
      out.write("						<ul class=\"nav nav-second-level\">\r\n");
      out.write("							<li><a href=\"hdbanhang\" class=\"active\">Bán hàng</a></li>\r\n");
      out.write("							<li><a href=\"hd_nh.html\">Nhập hàng</a></li>\r\n");
      out.write("						</ul></li>\r\n");
      out.write("					<li><a href=\"#\"><i class=\"fa fa-bar-chart-o fa-fw\"></i> Thống kê<span\r\n");
      out.write("						class=\"fa arrow\"></span></a>\r\n");
      out.write("						<ul class=\"nav nav-second-level\">\r\n");
      out.write("							<li><a href=\"tk_dt_bh.html\">Doanh thu bán hàng</a></li>\r\n");
      out.write("							<li><a href=\"tk_cp_nh.html\">Chi phí nhập hàng</a></li>\r\n");
      out.write("							<li><a href=\"tk_kh.html\">Khách hàng</a></li>\r\n");
      out.write("							<li><a href=\"tk_sp.html\">Sản phẩm</a></li>\r\n");
      out.write("						</ul></li>\r\n");
      out.write("					<li><a href=\"khachhang\"><i class=\"fa fa-users fa-fw\"></i>\r\n");
      out.write("							Khách hàng</a></li>\r\n");
      out.write("					<li><a href=\"nhan_vien.jsp\"><i class=\"fa fa-user fa-fw\"></i>\r\n");
      out.write("							Nhân viên</a></li>\r\n");
      out.write("					<li><a href=\"thongtintk\"><i\r\n");
      out.write("							class=\"fa fa-user-circle fa-fw\"></i> Thông tin tài khoản</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</aside>\r\n");
      out.write("		<!-- /.sidebar -->\r\n");
      out.write("\r\n");
      out.write("		<div id=\"page-wrapper\">\r\n");
      out.write("			<div class=\"container-fluid\">\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("					<div class=\"col-lg-12\">\r\n");
      out.write("						<h1 class=\"page-header\">Chi tiết hóa đơn bán hàng</h1>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("					<div class=\"col-lg-12 col-xlg-12 col-md-12  \">\r\n");
      out.write("						<div class=\"card\">\r\n");
      out.write("							<div class=\"card-body\">\r\n");
      out.write("								");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("								<form class=\"form-horizontal form-material mx-2\">\r\n");
      out.write("									<div class=\"form-group\">\r\n");
      out.write("										<label class=\"col-md-6 mb-0\">Mã hóa đơn: </label> <label\r\n");
      out.write("											class=\"col-md-6 mb-0\">Tên khách hàng: </label>\r\n");
      out.write("										<div class=\"col-md-6\">\r\n");
      out.write("											<input type=\"text\" placeholder=\"\"\r\n");
      out.write("												class=\"form-control ps-0 form-control-line\" required\r\n");
      out.write("												readonly value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${c1.ma_hd_bh}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"col-md-6\">\r\n");
      out.write("											<input type=\"text\" placeholder=\"\"\r\n");
      out.write("												class=\"form-control ps-0 form-control-line\" required\r\n");
      out.write("												readonly value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${c1.ten_kh}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"form-group\">\r\n");
      out.write("										<label for=\"example-email\" class=\"col-md-6\">Tên nhân\r\n");
      out.write("											viên:</label> <label class=\"col-md-6 mb-0\">Thời gian đặt\r\n");
      out.write("											hàng:</label>\r\n");
      out.write("										<div class=\"col-md-6\">\r\n");
      out.write("											<input type=\"text\" placeholder=\"\"\r\n");
      out.write("												class=\"form-control ps-0 form-control-line\"\r\n");
      out.write("												name=\"example-email\" id=\"example-email\" required readonly\r\n");
      out.write("												value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${c1.ten_nv}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"col-md-6\">\r\n");
      out.write("											<input type=\"text\" placeholder=\"\"\r\n");
      out.write("												class=\"form-control ps-0 form-control-line\" required\r\n");
      out.write("												readonly value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${c1.ngay_xuat_hd}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"form-group\">\r\n");
      out.write("										<label class=\"col-md-6 mb-0\">Tổng tiền:</label> <label\r\n");
      out.write("											class=\"col-md-6 mb-0\">Trạng thái:</label>\r\n");
      out.write("										<div class=\"col-md-6\">\r\n");
      out.write("											<input type=\"text\" placeholder=\"\"\r\n");
      out.write("												class=\"form-control ps-0 form-control-line\" required\r\n");
      out.write("												readonly\r\n");
      out.write("												value=\"");
      if (_jspx_meth_fmt_005fformatNumber_005f0(_jspx_page_context))
        return;
      out.write("đ\" />\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"col-md-6\">\r\n");
      out.write("											<input type=\"text\" placeholder=\"\"\r\n");
      out.write("												class=\"form-control ps-0 form-control-line\" required\r\n");
      out.write("												readonly value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${c1.trang_thai}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									<h3 class=\"center\">Danh sách hàng hóa đã mua</h3>\r\n");
      out.write("									<div class=\"table-responsive\">\r\n");
      out.write("										<table class=\"table table-striped table-bordered table-hover\"\r\n");
      out.write("											id=\"dataTables-example\" style=\"font-size: 1.2em;\">\r\n");
      out.write("											<thead>\r\n");
      out.write("												<tr>\r\n");
      out.write("													<th style=\"width: 30px; text-align: center;\">STT</th>\r\n");
      out.write("													<th style=\"width: 60px; text-align: center;\">Mã hàng\r\n");
      out.write("														hóa</th>\r\n");
      out.write("													<th style=\"width: 210px; text-align: center;\">Tên hàng\r\n");
      out.write("														hóa</th>\r\n");
      out.write("													<th style=\"width: 60px; text-align: center;\">Số lượng</th>\r\n");
      out.write("													<th style=\"width: 60px; text-align: center;\">Giá bán</th>\r\n");
      out.write("													<th style=\"width: 100px; text-align: center;\">Thành\r\n");
      out.write("														tiền</th>\r\n");
      out.write("												</tr>\r\n");
      out.write("											</thead>\r\n");
      out.write("											<tbody style=\"text-align: center;\">\r\n");
      out.write("												");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("											</tbody>\r\n");
      out.write("										</table>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"form-group\">\r\n");
      out.write("										<div class=\"col-sm-12 d-flex\">\r\n");
      out.write("											<a href=\"hdbanhang\"\r\n");
      out.write("												class=\"btn btn-info mx-auto mx-md-0 text-white\"> Thoát</a>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</form>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- jQuery -->\r\n");
      out.write("	<script src=\"js/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("	<!-- Bootstrap Core JavaScript -->\r\n");
      out.write("	<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("	<!-- Metis Menu Plugin JavaScript -->\r\n");
      out.write("	<script src=\"js/metisMenu.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("	<!-- DataTables JavaScript -->\r\n");
      out.write("	<script src=\"js/dataTables/jquery.dataTables.min.js\"></script>\r\n");
      out.write("	<script src=\"js/dataTables/dataTables.bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("	<!-- Custom Theme JavaScript -->\r\n");
      out.write("	<script src=\"js/startmin.js\"></script>\r\n");
      out.write("\r\n");
      out.write("	<!-- Page-Level Demo Scripts - Tables - Use for reference -->\r\n");
      out.write("	<script>\r\n");
      out.write("		$(document).ready(function() {\r\n");
      out.write("			$('#dataTables-example').DataTable({\r\n");
      out.write("				responsive : true\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /admin/hd_bh_ct.jsp(120,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("c1");
      // /admin/hd_bh_ct.jsp(120,8) name = value type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/admin/hd_bh_ct.jsp(120,8) '${requestScope.data1}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${requestScope.data1}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    boolean _jspx_th_fmt_005fformatNumber_005f0_reused = false;
    try {
      _jspx_th_fmt_005fformatNumber_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatNumber_005f0.setParent(null);
      // /admin/hd_bh_ct.jsp(159,19) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${c1.tong_tien}", java.lang.Object.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      // /admin/hd_bh_ct.jsp(159,19) name = type type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f0.setType("number");
      int _jspx_eval_fmt_005fformatNumber_005f0 = _jspx_th_fmt_005fformatNumber_005f0.doStartTag();
      if (_jspx_th_fmt_005fformatNumber_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f0);
      _jspx_th_fmt_005fformatNumber_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /admin/hd_bh_ct.jsp(186,12) name = items type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/admin/hd_bh_ct.jsp(186,12) '${requestScope.data2}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${requestScope.data2}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /admin/hd_bh_ct.jsp(186,12) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("c2");
      // /admin/hd_bh_ct.jsp(186,12) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVarStatus("status");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("													<tr class=\"odd gradeX\">\r\n");
            out.write("														<td style=\"vertical-align: middle;\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${status.index + 1}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("														<td style=\"vertical-align: middle;\">HH_");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${c2.ma_hang}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("														<td style=\"vertical-align: middle;\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${c2.ten_hang}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("														<td style=\"vertical-align: middle;\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${c2.so_luong}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("														<td style=\"vertical-align: middle;\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${c2.gia_ban}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("														<td style=\"vertical-align: middle;\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${c2.thanh_tien}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("													</tr>\r\n");
            out.write("												");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
